# <font color = 'dodgerblue'> **HW1  (15 Points):**</font>

**Required Submissions:**

You have to submit two files for this part of the  HW
1. FirstNameLastName_Hw1a.ipynb (colab notebook)
2. FirstNameLastName_Hw1a.pdf pdf file.

The pdf file is just the pdf version of colab notebook.


In [13]:
import torch
import time
import numpy as np
import matplotlib.pyplot as plt

In [14]:
torch.set_printoptions(precision=4, sci_mode=False)

 # <font color = 'dodgerblue'>**Q1 : Create Tensor (1 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [15]:
a = torch.zeros(5,3)
a[0,2]=10
a[2,0] = 100
a

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = 'dodgerblue'> **Q2: Reshape tensor (1 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [16]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [17]:
# code here
x = x.view(6,4)
x = torch.transpose(x, 0, 1)
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = 'dodgerblue'>**Question 3. Speedtest for vectorization - 2 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [22]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024,1024)
B = torch.randn(1024,1024)

In [19]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.020146846771240234 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

# code here

print("Matrix by vector: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

# code here

print("vector by vector: " + str(time.time()-start) + " seconds")

# <font color = 'dodgerblue'>**Question 4 : Redo Question 3 by using GPU - 2 Point**

<font size = 4, color = 'dodgerblue'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
## Solution 2
start=time.time()

C = # code here

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

# code here

print("Matrix by vector: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

# code here

print("vector by vector: " + str(time.time()-start) + " seconds")

# <font color = 'dodgerblue'>**Question 5. Memory efficient computation - 2 Points**</font>

We want to compute $C \leftarrow A \cdot B + C$, where $A, B$ and $C$ are all matrices. Implement this in the most memory efficient manner. Pay attention to the following two things:

1. Do not allocate new memory for the new value of $C$.
1. Do not allocate new memory for intermediate results if possible. Hint: If you implement this correcly the memory location of C given by id(C) will be same in both the cells below.

In [ ]:
A= torch.randn((1000, 1000),device=device)
B= torch.randn((1000,1000),device=device)
C= torch.randn((1000, 1000),device=device)
print(id(C))

In [ ]:
# your code here

print(id(C))

#<font color = 'dodgerblue'>**Question 6. Broadcast Operations - 2 Points**

In order to perform polynomial fitting we want to compute a design matrix $A$ with

$$A_{ij} = x_i^j$$

Our goal is to implement this **without a single for loop** entirely using vectorization and broadcast. Here $1 \leq j \leq 3$ and $x = \{1,2,3,4,5\}$. Implement code that generates following A matrix

$$\begin{bmatrix} 1 & 1 & 1 \\ 2 & 4 & 8 \\ 3 & 9 & 27 \\ 4 & 16 & 64 \\ 5 & 25 & 125\end{bmatrix}$$

In [ ]:
# your code here


# <font color = 'dodgerblue'> **Q7 Image Classification using - Pixel Similarity - 5 Points**

## <font color = 'dodgerblue'> **Import libraries**

In [ ]:
# import libraries
import torchvision
import torchvision.transforms as transforms
from pathlib import Path
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
import pandas as pd

## <font color = 'dodgerblue'> **Mount Google Deive**

In [ ]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## <font color = 'dodgerblue'>**Path to Dowanload Data**

<font color = 'dodgerblue'>**Make sure you change the Path to where you want to save data.**</font>
In the code below - **data/datasets** is the folder name in my google drive. You can change this to appropriate folder for your drive. For example you may want to save data to BUAN6341/HW1/Data. In this case the below code should be modified to :

 ```data_folder = Path('/content/drive/MyDrive/BUAN6341/HW2/Data')```

In [ ]:
data_folder = Path('YOUR PATH HERE')

## <font color = 'dodgerblue'>**Download MNIST training Data**
The MNIST is a dataset of  handwritten digits, available from this page http://yann.lecun.com/exdb/mnist/. It has a training set of 60,000 examples, and a test set of 10,000 examples. In this task we will use images for digits 3 and 7.

In [ ]:
trainset = torchvision.datasets.MNIST(root = data_folder,
                                      train = True,
                                      download = True,
                                      )

## <font color = 'dodgerblue'>**Subset of images**

trainset.data has images and trainset.targets has the labels. Below we will create a Boolean mask for digits 3 and 7. We will use this mask to extract subset of images.

In [ ]:
# get the mask
idx3 = trainset.targets==3
idx7 = trainset.targets==7

In [ ]:
idx3 # This take the value of True wherever the label was 3 and False otherwise

tensor([False, False, False,  ..., False, False, False])

In [ ]:
threes = trainset.data[idx3] # use Boolean mask to extract images for digit three
sevens = trainset.data[idx7] # use Boolean mask to extract images for digit seven

In [ ]:
threes.shape, sevens.shape

(torch.Size([6131, 28, 28]), torch.Size([6265, 28, 28]))

In [ ]:
type(threes[0])

torch.Tensor

In [ ]:
# get a sample image
sample_img_3 = threes[0]

In [ ]:
sample_img_3.shape

torch.Size([28, 28])

### <font color = 'dodgerblue'>**Task1**
Reshape the image so that it has following  shape: 28, 28, 1. Then convert the tensor to numpy array.

In [ ]:
sample_img_3_numpy =  # code here

In [ ]:
# let us look at the image
# the above steps were needed because the function cv2_imshow needs a three dimenional numpy array of the
# shape H x W  X C (height, width, number of channels). The number of channels for black and white images is 1.
cv2_imshow(sample_img_3_numpy)

### <font color = 'dodgerblue'>**Task2**

Repeat the above steps to show the first image for digit 7.
 - Get the first image.
 - Reshape the image to 28, 28, 1
 - Convert the tensor to numpy array


In [ ]:
# code here

## <font color = 'dodgerblue'>**Visualizing images as pixel values**

<font color = 'dodgerblue'>
- In a computer, images are stored in the form of matrices. The numbers in the matrix are called "pixel values."
- These pixel values show how bright each pixel is.
- 0 means "black," and 255 means "white."
- The matrix of numbers is called the channel, and there is only one channel in a grayscale image.
- For color inages , we have three channels(RGB - Red, Green Blue). That is we need three matrices to store color images.
</font>

In [ ]:
df = pd.DataFrame(sample_img_3[5:24, 7:22].numpy())
df.style.set_properties(**{'font-size':'8pt'})

<font color = 'dodgerblue'> - In the matrix below we have flipped color just for illustartion (We are using 0 for white instead of black).

In [ ]:
df.style.set_properties(**{'font-size':'8pt'}).background_gradient('Greys')

### <font color = 'dodgerblue'>**Task3**

<font color = 'dodgerblue'>**Convert threes and sevens generated earlier to float and and take the mean along dimension 0.**

Hint(You can use tensor.float() and then take the mean along dimesnion 0.

Here we are generating an average image by taking the average of each pixel across images.

In [ ]:
mean_threes =  # code here
mean_sevens =  # code here

In [ ]:
mean_threes.shape
mean_sevens.shape

torch.Size([28, 28])

In [ ]:
cv2_imshow(mean_threes.unsqueeze(dim=2).numpy())
print()
cv2_imshow(mean_sevens.unsqueeze(dim=2).numpy())

## <font color = 'dodgerblue'>**Prediction for validation images**

We will calculate the distance of each validation image from the mean_threes and mean_sevens. If the validation image is closest to mean_threes then we will predict 1 else we will predict 0.

## <font color = 'dodgerblue'>**Get Valid Dataset**

In [ ]:
validset = torchvision.datasets.MNIST(root = data_folder,
                                      train = False,
                                      download = True,
                                      )

In [ ]:
# get the mask
idx3 = validset.targets==3
idx7 = validset.targets==7

In [ ]:
validset.data.shape

torch.Size([10000, 28, 28])

In [ ]:
# get images and labels using the mask
valid_data_3_7 = validset.data[idx3+idx7]
valid_targets_3_7 = validset.targets[idx3 + idx7]

In [ ]:
# check the shape of the inputs (images)
# we have 2038 images with size 28 x 28.
valid_data_3_7.shape

torch.Size([2038, 28, 28])

In [ ]:
# lables for valid dataset
valid_targets_3_7

tensor([7, 7, 3,  ..., 3, 7, 3])

In [ ]:
# change the lable to 1 where the label was 3
valid_targets_3_7[valid_targets_3_7==3] = 1

In [ ]:
# change the lable to 0 where the label was 7
valid_targets_3_7[valid_targets_3_7==7] = 0

In [ ]:
valid_targets_3_7.unique()

tensor([0, 1])

In [ ]:
valid_targets_3_7

tensor([0, 0, 1,  ..., 1, 0, 1])

In [ ]:
valid_data_3_7.shape

torch.Size([2038, 28, 28])

## <font color = 'dodgerblue'>**Distance between images**

### <font color = 'dodgerblue'>**Task4**

<font color = 'dodgerblue'>**Write a function to calculate the distance between two images a and b.**
 - Calculate the difference between corresponding pixels of two images.
 - Calculate square of differences.
 - Take the mean (take the mean across last two dimensions (-1, -2) of the square of the differences and then take the square root.

In [ ]:
def dist_images(a, b):
  # code here

In [ ]:
# calculate the distance of the each image in validation set from mean_threes
# bacause of the  broadcasting we are able to use the above function which was written to
# calculate the distnace between two images
valid_3_dist = dist_images(valid_data_3_7, mean_threes)

In [ ]:
# calculate the distance of the each image in validation set from mean_sevens
valid_7_dist = dist_images(valid_data_3_7, mean_sevens)

In [ ]:
# if you have done everything right, you will observe following shapes.
valid_3_dist.shape, valid_7_dist.shape

(torch.Size([2038]), torch.Size([2038]))

## <font color = 'dodgerblue'>**Prediction Using Distance**

### <font color = 'dodgerblue'>**Task5**



In [ ]:
# step 1 : generate the tensor filled with zeros that has the same shape as valid_target_3_7
prediction =  # code here

In [ ]:
# step 2: update the tensor prediction. Update the value to 1, when valid_3_dist < valid_7_dist.
# Hint (Generate a Boolean mask using the condition valid_3_dist < valid_7_dist and use the mask to update value to 1 )

# code here

In [ ]:
prediction

tensor([0, 0, 1,  ..., 1, 0, 1])

## <font color = 'dodgerblue'>**Accuracy**

In [ ]:
correct = prediction == valid_targets_3_7

In [ ]:
correct

tensor([True, True, True,  ..., True, True, True])

In [ ]:
100 * correct.float().mean().item()

96.6143250465393